<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_registration"
 *
 * Auto generated by Extension Builder 2014-06-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'RKW Registration',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Steffen Kroggel, Maximilian Fäßler',
	'author_email' => 'developer@steffenkroggel.de, faesslerweb@web.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '9.5.0',
	'constraints' => [
		'depends' => [
            'typo3' => '9.5.0-9.5.99',
            'rkw_basics' => '9.5.0-9.5.99',
            'rkw_mailer' => '9.5.0-9.5.99',
            'rkw_ajax' => '9.5.0-9.5.99',
        ],
		'conflicts' => [
		],
		'suggests' => [
		],
	],
];
